name: Deploy GitHub Release Assets

on:
  workflow_call:
    secrets:
      TOKEN_TO_UPLOAD_ASSETS:
        required: true

jobs:
  deploy_github_release_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          name: deb-deliverables
          path: ./
      - uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          name: rpm-deliverables
          path: ./
      - uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          name: windows-deliverables
          path: ./
      - uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          name: macos-deliverables
          path: ./
      - uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          name: target
          path: ./target/

      - run: ls -l

      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha256sum
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.deb.sha512sum
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./target/*.jar
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.rpm
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.rpm.sha256sum
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*.rpm.sha512sum
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./*-windows-x64.zip
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./semvery-*.exe
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./semvery-*.msi
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./semvery-*-macos-*.zip
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./semvery-*.dmg
      - uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./semvery-*.pkg
